server.port=${PORT:10000}
spring.application.name=backend
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres?sslmode=require}
spring.datasource.username=${DATABASE_USERNAME:postgres.qjpcqprzhglmqcimjhic}
spring.datasource.password=${DATABASE_PASSWORD:d75yXnDNVpP9etCc}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.connection-timeout=10000

spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

app.security.enabled=${SECURITY_ENABLED:false}

supabase.url=${SUPABASE_URL:https://qjpcqprzhglmqcimjhic.supabase.co}
supabase.key=${SUPABASE_KEY:sb_publishable_2jLpf9BSWVUW2foYtRSdwg_Yoe6s1xK}
